const PALETTE = {
  PRIMARY_VIOLET_BG: '#F2ECFF',
  DEFAULT_VIOLET_HIGHLIGHT: '#D5C2FF',
  PRIMARY_VIOLET_TEXT: '#b5a0e8',
  HIGHLIGHT_GREEN: '#93B95C',

  DEFAULT_WHITE: '#ffffff',
  DEFAULT_BEIGE: '#F7EED3',
  DEFAULT_GRAY: '#777777',
  DEFAULT_GREEN: '#DEE5D4',
  DEFAULT_BUTTER: '#FEF9D9',

  BUTTON_RED: '#FF5F5A',
  BUTTON_YELLOW: '#FFBE2E',
  BUTTON_GREEN: '#2ACA44',

  TERMINAL_BLACK: '#2D2A2E',
  CMD_WHITE: '#F8F8F6',
  CMD_FUCHSIA: '#FF6188',
  BORDER_GRAY: '#c3c3c3',
};

export default PALETTE;
